export const myData = [
  { key: "Mt 1–2", name: "Matthew 1-2" },
  { key: "Mt 3–4", name: "Matthew 3-4" },
  { key: "Mt 5", name: "Matthew 5" },
  { key: "Mt 6", name: "Matthew 6" },
  { key: "Mt 7", name: "Matthew 7" },
  { key: "Mt 8", name: "Matthew 8" },
  { key: "Mt 9", name: "Matthew 9" },
  { key: "Mt 10", name: "Matthew 10" },
  { key: "Mt 11", name: "Matthew 11" },
  { key: "Mt 12", name: "Matthew 12" },
  { key: "Mt 13", name: "Matthew 13" },
  { key: "Mt 14", name: "Matthew 14" },
  { key: "Mt 15", name: "Matthew 15" },
  { key: "Mt 16–17", name: "Matthew 16-17" },
  { key: "Mt 18", name: "Matthew 18" },
  { key: "Mt 19", name: "Matthew 19" },
  { key: "Mt 20", name: "Matthew 20" },
  { key: "Mt 21", name: "Matthew 21" },
  { key: "Mt 22", name: "Matthew 22" },
  { key: "Mt 23", name: "Matthew 23" },
  { key: "Mt 24", name: "Matthew 24" },
  { key: "Mt 25", name: "Matthew 25" },
  { key: "Mt 26", name: "Matthew 26" },
  { key: "Mt 27", name: "Matthew 27" },
  { key: "Mt 28–Mk 1", name: "Matthew 28-Mark 1" },
  { key: "Mk 2", name: "Mark 2" },
  { key: "Mk 3", name: "Mark 3" },
  { key: "Mk 4", name: "Mark 4" },
  { key: "Mk 5", name: "Mark 5" },
  { key: "Mk 6", name: "Mark 6" },
  { key: "Mk 7", name: "Mark 7" },
  { key: "Mk 8", name: "Mark 8" },
  { key: "Mk 9", name: "Mark 9" },
  { key: "Mk 10", name: "Mark 10" },
  { key: "Mk 11", name: "Mark 11" },
  { key: "Mk 12", name: "Mark 12" },
  { key: "Mk 13", name: "Mark 13" },
  { key: "Mk 14", name: "Mark 14" },
  { key: "Mk 15", name: "Mark 15" },
  { key: "Mk 16", name: "Mark 16" },
  { key: "Lk 1", name: "Luke 1" },
  { key: "Lk 2", name: "Luke 2" },
  { key: "Lk 3", name: "Luke 3" },
  { key: "Lk 4", name: "Luke 4" },
  { key: "Lk 5", name: "Luke 5" },
  { key: "Lk 6", name: "Luke 6" },
  { key: "Lk 7", name: "Luke 7" },
  { key: "Lk 8", name: "Luke 8" },
  { key: "Lk 9", name: "Luke 9" },
  { key: "Lk 10", name: "Luke 10" },
  { key: "Lk 11", name: "Luke 11" },
  { key: "Lk 12", name: "Luke 12" },
  { key: "Lk 13", name: "Luke 13" },
  { key: "Lk 14", name: "Luke 14" },
  { key: "Lk 15", name: "Luke 15" },
  { key: "Lk 16", name: "Luke 16" },
  { key: "Lk 17", name: "Luke 17" },
  { key: "Lk 18", name: "Luke 18" },
  { key: "Lk 19", name: "Luke 19" },
  { key: "Lk 20", name: "Luke 20" },
  { key: "Lk 21", name: "Luke 21" },
  { key: "Lk 22", name: "Luke 22" },
  { key: "Lk 23", name: "Luke 23" },
  { key: "Lk 24", name: "Luke 24" },
  { key: "Jn 1", name: "John 1" },
  { key: "Jn 2", name: "John 2" },
  { key: "Jn 3", name: "John 3" },
  { key: "Jn 4", name: "John 4" },
  { key: "Jn 5", name: "John 5" },
  { key: "Jn 6", name: "John 6" },
  { key: "Jn 7", name: "John 7" },
  { key: "Jn 8", name: "John 8" },
  { key: "Jn 9", name: "John 9" },
  { key: "Jn 10", name: "John 10" },
  { key: "Jn 11", name: "John 11" },
  { key: "Jn 12", name: "John 12" },
  { key: "Jn 13", name: "John 13" },
  { key: "Jn 14", name: "John 14" },
  { key: "Jn 15", name: "John 15" },
  { key: "Jn 16", name: "John 16" },
  { key: "Jn 17", name: "John 17" },
  { key: "Jn 18", name: "John 18" },
  { key: "Jn 19", name: "John 19" },
  { key: "Jn 20", name: "John 20" },
  { key: "Jn 21–Acts 1", name: "John 21-Acts 1" },
  { key: "Acts 2", name: "Acts 2" },
  { key: "Acts 3", name: "Acts 3" },
  { key: "Acts 4", name: "Acts 4" },
  { key: "Acts 5", name: "Acts 5" },
  { key: "Acts 6", name: "Acts 6" },
  { key: "Acts 7", name: "Acts 7" },
  { key: "Acts 8", name: "Acts 8" },
  { key: "Acts 9", name: "Acts 9" },
  { key: "Acts 10", name: "Acts 10" },
  { key: "Acts 11", name: "Acts 11" },
  { key: "Acts 12", name: "Acts 12" },
  { key: "Acts 13", name: "Acts 13" },
  { key: "Acts 14", name: "Acts 14" },
  { key: "Acts 15", name: "Acts 15" },
  { key: "Acts 16", name: "Acts 16" },
  { key: "Acts 17", name: "Acts 17" },
  { key: "Acts 18", name: "Acts 18" },
  { key: "Acts 19", name: "Acts 19" },
  { key: "Acts 20", name: "Acts 20" },
  { key: "Acts 21", name: "Acts 21" },
  { key: "Acts 22", name: "Acts 22" },
  { key: "Acts 23", name: "Acts 23" },
  { key: "Acts 24–25", name: "Acts 24-25" },
  { key: "Acts 26", name: "Acts 26" },
  { key: "Acts 27", name: "Acts 27" },
  { key: "Acts 28", name: "Acts 28" },
  { key: "Rom 1", name: "Romans 1" },
  { key: "Rom 2", name: "Romans 2" },
  { key: "Rom 3–4", name: "Romans 3-4" },
  { key: "Rom 5–6", name: "Romans 5-6" },
  { key: "Rom 7", name: "Romans 7" },
  { key: "Rom 8", name: "Romans 8" },
  { key: "Rom 9–10", name: "Romans 9-10" },
  { key: "Rom 11", name: "Romans 11" },
  { key: "Rom 12–13", name: "Romans 12-13" },
  { key: "Rom 14–15", name: "Romans 14-15" },
  { key: "Rom 16–1 Cor 1", name: "Romans 16-1 Corinthians 1" },
  { key: "1 Cor 2–3", name: "1 Corinthians 2-3" },
  { key: "1 Cor 4–5", name: "1 Corinthians 4-5" },
  { key: "1 Cor 6–7", name: "1 Corinthians 6-7" },
  { key: "1 Cor 8–9", name: "1 Corinthians 8-9" },
  { key: "1 Cor 10", name: "1 Corinthians 10" },
  { key: "1 Cor 11", name: "1 Corinthians 11" },
  { key: "1 Cor 12–13", name: "1 Corinthians 12-13" },
  { key: "1 Cor 14", name: "1 Corinthians 14" },
  { key: "1 Cor 15", name: "1 Corinthians 15" },
  { key: "1 Cor 16–2 Cor 1", name: "1 Corinthians 16-2 Corinthians 1" },
  { key: "2 Cor 2–4", name: "2 Corinthians 2-4" },
  { key: "2 Cor 5–6", name: "2 Corinthians 5-6" },
  { key: "2 Cor 7–8", name: "2 Corinthians 7-8" },
  { key: "2 Cor 9–10", name: "2 Corinthians 9-10" },
  { key: "2 Cor 11–12", name: "2 Corinthians 11-12" },
  { key: "2 Cor 13–Gal 1", name: "2 Corinthians 13-Galatians 1" },
  { key: "Gal 2–3", name: "Galatians 2-3" },
  { key: "Gal 4–5", name: "Galatians 4-5" },
  { key: "Gal 6–Eph 1", name: "Galatians 6-Ephesians 1" },
  { key: "Eph 2–3", name: "Ephesians 2-3" },
  { key: "Eph 4", name: "Ephesians 4" },
  { key: "Eph 5", name: "Ephesians 5" },
  { key: "Eph 6–Phil 1", name: "Ephesians 6-Philippians 1" },
  { key: "Phil 2–3", name: "Philippians 2-3" },
  { key: "Phil 4–Col 1", name: "Philippians 4-Colossians 1" },
  { key: "Col 2–3", name: "Colossians 2-3" },
  { key: "Col 4–1 Thes 2", name: "Colossians 4-1 Thessalonians 2" },
  { key: "1 Thes 3–4", name: "1 Thessalonians 3-4" },
  { key: "1 Thes 5–2 Thes 1", name: "1 Thessalonians 5-2 Thessalonians 1" },
  { key: "2 Thes 2–3", name: "2 Thessalonians 2-3" },
  { key: "1 Tm 1–3", name: "1 Timothy 1-3" },
  { key: "1 Tm 4–5", name: "1 Timothy 4-5" },
  { key: "1 Tm 6–2 Tm 1", name: "1 Timothy 6-2 Timothy 1" },
  { key: "2 Tm 2–3", name: "2 Timothy 2-3" },
  { key: "2 Tm 4–Ti 2", name: "2 Timothy 4-Titus 2" },
  { key: "Ti 3–Phlm", name: "Titus 3-Philemon" },
  { key: "Heb 1–3", name: "Hebrews 1-3" },
  { key: "Heb 4–6", name: "Hebrews 4-6" },
  { key: "Heb 7–8", name: "Hebrews 7-8" },
  { key: "Heb 9", name: "Hebrews 9" },
  { key: "Heb 10", name: "Hebrews 10" },
  { key: "Heb 11", name: "Hebrews 11" },
  { key: "Heb 12–13", name: "Hebrews 12-13" },
  { key: "Jas 1–2", name: "James 1-2" },
  { key: "Jas 3–5", name: "James 3-5" },
  { key: "1 Pt 1–2", name: "1 Peter 1-2" },
  { key: "1 Pt 3–4", name: "1 Peter 3-4" },
  { key: "1 Pt 5–2 Pt 2", name: "1 Peter 5-2 Peter 2" },
  { key: "2 Pt 3–1 Jn 2", name: "2 Peter 3-1 John 2" },
  { key: "1 Jn 3–4", name: "1 John 3-4" },
  { key: "1 Jn 5–3 Jn", name: "1 John 5-3 John" },
  { key: "Jude 1–Rv 1", name: "Jude 1-Revelation 1" },
  { key: "Rv 2–3", name: "Revelation 2-3" },
  { key: "Rv 4–6", name: "Revelation 4-6" },
  { key: "Rv 7–9", name: "Revelation 7-9" },
  { key: "Rv 10–12", name: "Revelation 10-12" },
  { key: "Rv 13–15", name: "Revelation 13-15" },
  { key: "Rv 16–17", name: "Revelation 16-17" },
  { key: "Rv 18–20", name: "Revelation 18-20" },
  { key: "Rv 21–22", name: "Revelation 21-22" }
];
